package sambal.mydd.app.constant

interface KeyConstant {
    companion object {
        const val KEY_RESPONSE = "response"
        const val KEY_RESULT = "result"
        const val KEY_MESSAGE = "message"
        const val KEY_ERROR_TYPE = "error_type"
        const val KEY_STATUS = "status"
        const val KEY_SUCCESS = "success"
        const val KEY_RESPONSE_CODE_200 = "200"
        const val KEY_RESPONSE_CODE_202 = "202"
        const val KEY_RESPONSE_CODE_203 = "203"
        const val KEY_RESPONSE_CODE_201 = "201"
        const val KEY_MESSAGE_FALSE = "false"
        const val KEY_MESSAGE_True = "true"
        const val KEY_SKIP = "skip"
        const val KEY_OPEN_PROMOCODE = "promo"

        //-------------------------PUBNUB CHAT------------------------------//
        const val PUBNUB_PUBLISH_KEY = "pub-c-1d970180-6a36-4b44-a730-a66292f717f6"
        const val PUBNUB_SUBSCRIBE_KEY = "sub-c-3ffc7320-905e-11ea-8504-ea59babdc551"

        //------------------------------------------------------------//
        const val KEY_SOCIAL_LOGIN_INPUT_TOKEN = "inputToken"
        const val KEY_GRANT_TYPE = "grant_type"
        const val KEY_CLIENT_ID = "client_id"
        const val KEY_GRANT_TYPE_VALUE = "password"
        const val KEY_CLIENT_ID_VALUE = "dealDio"
        const val KEY_CLIENT_SEC = "client_secret"
        const val KEY_CLIENT_SEC_VALUE = "de@lDiONgR"
        const val KEY_ACCESS_TOKEN = "access_token"
        const val KEY_REFRESH_TOKEN = "refresh_token"
        const val KEY_NAME = "name"
        const val KEY_GOOGLE_API_KEY = "google_api_key"
        const val KEY_SHARE_URL = "shareURL"
        const val KEY_USER_MOBILE = "userMobile"
        const val KEY_DEVICE_ID = "deviceID"
        const val KEY_MOBILE_TYPE = "mobileType"
        const val KEY_REFERRAL_CODE = "userReferralCode"
        const val KEY_USER_TYPE = "userType"
        const val KEY_EMAIL = "userEmail"
        const val KEY_DEVICE_TOKEN = "device_token"
        const val KEY_DEVICE_MODE = "device_mode"
        const val KEY_PASSWORD = "password"
        const val KEY_USER_FILE = "userfile"
        const val KEY_USER_UUID = "userQRuuid"
        const val KEY_USER_COUNTRY = "userCountry"
        const val KEY_USER_COUNTRY_ID = "userCountryId"
        const val KEY_USER_COUNTRY_CODE = "userCountryCode"
        const val KEY_USER_PROFILE_NAME = "userProfileName"
        const val KEY_USER_PHOTO = "userPhoto"
        const val KEY_USER_BANNER_IMAGE = "userBannerImage"
        const val KEY_USER_CURRENCY = "userCurrency"
        const val KEY_POST_EMAIL = "email"
        const val KEY_LATITUDE = "latitude"
        const val KEY_LONG = "long"
        const val KEY_CODE = "code"
        const val KEY_USER_KEY = "userKey"
        const val DEVICE_TYPE_VALUE = "A"
        const val SIGN_UP_WITH_EMAIL = 1
        const val SIGN_UP_WITH_GOOGLE = 3
        const val KEY_WALLET_USER_BALANCE_MINUTES = "userBalanceMinutes"

        //DealDio Keys
        const val KEY_FAVOURITE_PRODUCT_LIST = "favouriteProductList"
        const val KEY_AGENT_DETAILS = "agentDetails"
        const val KEY_PRODUCT_ID = "productId"
        const val KEY_PRODUCT_NAME = "productName"
        const val KEY_PRODUCT_AGENT_NAME = "productAgentName"
        const val KEY_PRODUCT_CATEGORY_NAME = "productCategoryName"
        const val KEY_PRODUCT_DESC = "productDesc"
        const val KEY_PRODUCT_CATEGORY_ID = "productCategoryId"
        const val KEY_PRODUCT_LOCATION = "productLocation"
        const val KEY_PRODUCT_FAVORITE = "productFavourite"
        const val KEY_PRODUCT_IMAGE = "productImage"
        const val KEY_PRODUCT_CURRENCY = "productCurrency"
        const val KEY_PRODUCT_DISCOUNT_PERCENTAGE = "productDiscountPercentage"
        const val KEY_PRODUCT_PRICE = "productPrice"
        const val KEY_PRODUCT_FINAL_PRICE = "productFinalPrice"
        const val KEY_PRODUCT_TOTAL_REDEEOM = "productTotalReedom"
        const val KEY_PRODUCT_TYPE = "productType"
        const val KEY_PRODUCT_TYPE_ID = "productTypeId"
        const val KEY_DEAL_EXPIRED_DATE = "dealExpiredDate"
        const val KEY_OFFER_GIFT_ENABLED = "offerGiftEnabled"
        const val KEY_GIFT_DESCRIPTION = "offerGiftDescription"
        const val KEY_OFFER_TYPE_ID = "offerTypeId"
        const val KEY_PRICE_ENABLED_ID = "priceEnabledId"
        const val KEY_DISCOUNT_PRICE_ENABLED_ID = "discountPriceEnabledId"
        const val KEY_PRODUCT_DISCOUNT_PERCENTAGE_ENABLED = "productDiscountPercentageEnabled"
        const val KEY_PRODUCT_DISTANCE = "productDistance"
        const val KEY_MORE_PRODUCT = "moreProduct"
        const val KEY_MORE_VOUCHERS = "moreVouchers"
        const val KEY_DEAL_BUTTON_ENABLE = "dealButtonEnable"
        const val KEY_AGENT_LIST = "agentList"
        const val KEY_AGENT_ID = "agentId"
        const val KEY_AGENT_ADDRESS = "agentAddress"
        const val KEY_AGENT_IMAGE = "agentImage"
        const val KEY_AGENT_DESCRIPTION = "agentDescription"
        const val KEY_PRODUCT_AGENT_ID = "productAgentId"
        const val KEY_AGENT_ENABLE_DESCRIPTION = "agentEnableDescription"
        const val KEY_AGENT_DISTANCE = "agentDistance"
        const val KEY_AGENT_LATITUDE = "agentLatitude"
        const val KEY_AGENT_LONGITUDE = "agentLongitude"
        const val KEY_AGENT_VOUCHER_ENABLED = "agentVoucherEnabled"
        const val KEY_AGENT_DEAL_ENABLED = "agentDealEnabled"
        const val KEY_AGENT_COMPANY_NAME = "agentCompanyName"
        const val KEY_AGENT_EMAIL = "agentEmail"
        const val KEY_AGENT_MOBILE = "agentMobile"
        const val KEY_AGENT_COUNTRY = "agentCountry"
        const val KEY_AGENT_COUNTRY_CODE = "agentCountryCode"
        const val KEY_AGENT_RATING = "agentRating"
        const val KEY_AGENT_URL = "agentURL"
        const val KEY_AGENT_ADS_ENABLE = "agentAdsEnable"
        const val KEY_AGENT_FB_URL = "agentFacebookURL"
        const val KEY_AGENT_INSTA_URL = "agentInstagramURL"
        const val KEY_AGENT_YOUTUBE_URL = "agentYoutubeURL"
        const val KEY_BANNER_LIST = "bannerList"
        const val KEY_TIMING_LIST = "timingList"
        const val KEY_BANNER_IMAGE_URL = "bannerImageURL"
        const val KEY_BANNER_VIDEO_URL = "bannerVideoURL"
        const val KEY_BANNER_TYPE = "bannerType"
        const val KEY_YOUTUBE_VIDEO_ID = "youtubeVideoId"
        const val KEY_BANNER_VIDEO_TYPE = "bannerVideoType"
        const val KEY_CORPORATE_DEAL = "corporateDeal"
        const val KEY_MORE_PRODUCT_TEXT = "moreProductText"
        const val KEY_AGENT_EXTERNAL_URL_ENABLE = "agentExternalURLEnable"
        const val KEY_AGENT_EXTERNAL_URL = "agentExternalURL"
        const val KEY_NOTI_ID = "notificationId"
        const val KEY_NOTIFICATION_LIST = "notification"
        const val KEY_DEALS_LIST = "dealsList"
        const val KEY_OFFER_LIMITED_ENABLED = "offerLimitedEnabled"
        const val KEY_USER_DETAILS = "userDetails"
        const val KEY_USER_ID = "userId"
        const val KEY_USER_NAME = "userName"
        const val KEY_SCAN_AGENT = "secure/scanAgentUUIDForRedeem"
        const val QRCode_bitmap = "QRCode_bitmap"
        const val KEY_AGENT_VIBER_NUMBER = "agentViberNumber"

        /*SharedPrefrence KEY*/
        const val Shar_Name = "Name"
        const val Shar_Email = "Emmail"
        const val Shar_Phone = "Phone"
        const val Shar_Photo = "Photo"
        const val Shar_DeviceID = "DeviceId"
    }
}